name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install isort black flake8 bandit pip-audit
      - name: Check imports and formatting
        run: |
          isort --check-only .
          black --check .
      - name: Lint with flake8
        run: flake8 .
      - name: Security scan with bandit
        run: bandit -r src
      - name: Dependency audit
        run: pip-audit
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install project dependencies with Poetry
        run: poetry install
      - name: List Poetry environment packages
        run: poetry run pip list
      - name: Run tests with coverage
        run: |
            export PYTHONPATH=src
            poetry run pytest --cov=src --cov-report=term --cov-report=xml
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage.xml
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}

